### ISSUE TITLE
Less than 12p predictions on Apexchart unreadable

### ISSUE THREAD

**Issue by prestonsmartuk** [fboundy/agile_predict#3]
Hi,

Recent update to Apexchart has made your Yaml configuration predictions unreadable if less than 12p. You now cannot hover over that time section to understand the price prediction.

See screenshot below and red line. 

<img width="1176" alt="Screenshot 2024-07-13 at 14 21 52" src="https://github.com/user-attachments/assets/0097f695-63dd-4441-a571-19dca856c2a6">

**Comment by heisenberg2980** [comment]
Same issue here

**Comment by heisenberg2980** [comment]
Same issue here.

@fboundy is there any parameter or option we have missed to avoid this issue?

**Comment by alfwro13** [comment]
I had the same issue so I manually specified the bottom range (min: -2) :
````
type: custom:apexcharts-card
apex_config: null
header:
  show: true
  show_states: true
  colorize_states: true
graph_span: 7d
yaxis:
  - id: price
    min: -2
[rest of the code]
````
